name: comfy_pants
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=0.24.2
  - scikit-learn=0.22.1
  - numpy=1.18.1
  - nilearn=0.6.1
  - matplotlib=3.1.3
  - seaborn=0.10.0
  - python=3.7
  - ipykernel=5.1.4
  - pip:
    - pybids==0.10.0

